// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type Chapter struct {
	ChapterID   string `json:"chapterID"`
	Title       string `json:"title"`
	ArabicTitle string `json:"arabicTitle"`
	Description string `json:"description"`
}

type ClassRoom struct {
	ClassRoomID  string  `json:"classRoomID"`
	Title        string  `json:"title"`
	Image        string  `json:"image"`
	Price        int     `json:"price"`
	Badge        string  `json:"badge"`
	StudentCount int     `json:"studentCount"`
	Rating       float64 `json:"Rating"`
}

type CreateChapterInput struct {
	ClassRoomID string `json:"classRoomID"`
	Title       string `json:"title"`
	ArabicTitle string `json:"arabicTitle"`
	Description string `json:"description"`
}

type CreateLessonInput struct {
	ChapterID   string `json:"chapterID"`
	Title       string `json:"title"`
	ArabicTitle string `json:"arabicTitle"`
	Description string `json:"description"`
}

type Lesson struct {
	LessonID    string `json:"lessonID"`
	Title       string `json:"title"`
	ArabicTitle string `json:"arabicTitle"`
	Description string `json:"description"`
}

type Mutation struct {
}

type OperationStatus struct {
	Succeeded bool `json:"succeeded"`
}

type Query struct {
}

type UploadVideoInput struct {
	LessonID string         `json:"lessonID"`
	Content  graphql.Upload `json:"content"`
}
