// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ClassRoom struct {
	ClassRoomID  string    `json:"classRoomID"`
	Title        string    `json:"title"`
	Image        string    `json:"image"`
	Price        int       `json:"price"`
	Badge        string    `json:"badge"`
	StudentCount int       `json:"studentCount"`
	Rating       float64   `json:"Rating"`
	Lessons      []*Lesson `json:"lessons"`
}

type Lesson struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	ArabicTitle string `json:"arabicTitle"`
}

type Mutation struct {
}

type OperationStatus struct {
	Succeeded bool `json:"succeeded"`
}

type Query struct {
}
